openapi: 3.0.0
info:
  title: CALIUSO Memory API
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /memory/store:
    post:
      summary: Store memory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                memory:
                  type: object
      responses:
        '200':
          description: Memory stored

  /memory/fetch:
    get:
      summary: Fetch memory
      parameters:
        - name: session_id
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Memory fetched

  /memory/clear:
    delete:
      summary: Clear memory
      parameters:
        - name: session_id
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Memory cleared
