services:
  - type: web
    name: caliuso-memory-core
    runtime: python
    buildCommand: ""
    startCommand: uvicorn caliuso_memory_api:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000